demo_django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("documents/", include('documents.urls')),
    path("tasks/", include('tasks.urls')),
]

documents/urls.py
from django.urls import path

from .views import DocumentCreateView, DocumentListView, DocumentDeleteView, show_document_file

app_name = 'documents'

urlpatterns = [
    path('', DocumentListView.as_view(), name='list-document'),
    path('new', DocumentCreateView.as_view(), name='create-document'),
    path('delete/<int:pk>', DocumentDeleteView.as_view(), name='delete-document'),
    path('<int:pk>', show_document_file, name='show-document')
]

tasks/urls.py
from django.urls import path
from .views import TaskCreateView, TaskListView, TaskUpdateView, TaskDeleteView

app_name = 'tasks'

urlpatterns = [
    path('', TaskListView.as_view(), name='task-list'),
    path('new', TaskCreateView.as_view(), name='task-create'),
    path("<int:pk>/update", TaskUpdateView.as_view(), name='task-update'),
    path("<int:pk>/delete", TaskDeleteView.as_view(), name='task-delete')
]

documents/models.py
from pathlib import Path

from django.core.validators import FileExtensionValidator
from django.db import models


# Create your models here.
class Document(models.Model):
    file = models.FileField(upload_to="uploads/", max_length=100,
                            validators=[FileExtensionValidator(['pdf', 'jpeg', 'png', 'gif', 'tiff'])])

    def get_file_name(self):
        return Path(self.file.url).name

    def __str__(self):
        return self.get_file_name()

tasks/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    text = models.CharField(max_length=512)

documents/views.py
import re
from pathlib import Path

from django.forms import ClearableFileInput
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from django.views.static import serve

from documents.models import Document


class DocumentCreateView(generic.CreateView):
    # form_class = DocumentForm
    model = Document
    fields = ('file',)

    def get_success_url(self):
        return reverse_lazy('documents:list-document')

    def post(self, request, *args, **kwargs):
        files = request.FILES.getlist('file')
        for index, file in enumerate(files[:-1]):
            Document.objects.create(file=file)
        if 'document-create-save' in request.POST:
            return super().post(request, *args, **kwargs)
        else:
            raise ValueError()

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['form'].fields['file'].widget = ClearableFileInput(attrs={'multiple': True})
    #     context['document'] = None
    #     return context


class DocumentListView(generic.ListView):
    model = Document


def remove_file_and_parent_if_empty(path):
    if isinstance(path, str):
        path = Path(path)
    parent = path.parent
    try:
        Path.rmdir(path)
        remove_file_and_parent_if_empty(parent)
    except NotADirectoryError:
        Path.unlink(path)
        remove_file_and_parent_if_empty(parent)
    except OSError:
        pass


class DocumentDeleteView(generic.DeleteView):
    model = Document

    def get_success_url(self):
        return reverse_lazy('documents:list-document')

    def dispatch(self, request, *args, **kwargs):
        print('Removing file', self.get_object().file.path)
        remove_file_and_parent_if_empty(self.get_object().file.path)
        return super().dispatch(request, *args, **kwargs)


def show_document_file(request, pk):
    document = get_object_or_404(Document, pk=pk)
    response = HttpResponse(status=200)
    response['Content-Type'] = ''
    response['X-Accel-Redirect'] = f"{document.file.url}"
    return response

tasks/views.py
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
from django.shortcuts import reverse
from tasks.models import Task


class TaskCreateView(CreateView):
    model = Task
    fields = ['text']

    def get_success_url(self):
        return reverse('tasks:task-list')


class TaskListView(ListView):
    model = Task


class TaskUpdateView(UpdateView):
    model = Task
    fields = ['text']


class TaskDeleteView(DeleteView):
    model = Task

    def get_success_url(self):
        return reverse('tasks:task-list')

documents/templates/documents/document_form.html
{% extends 'base.html' %}
{% block title %}
New Document
{% endblock %}

{% block main %}
<div class="document-form">
    <div>
        New Document
    </div>
    <form method="POST" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" name="document-create-save" value="Save">
    </form>
</div>
{% endblock %}

documents/templates/documents/document_list.html
{% extends 'base.html' %}
{% block title %}
    Documents
{% endblock %}
{% block main %}
    <div class="document-list">
        <p><a href="{% url 'documents:create-document' %}">Add Document</a></p>
        <br>
        {% if not object_list %}
            <p>You have no Documents yet!</p>
        {% else %}
            {% for document in object_list %}
                <div class=document-list__row>
                    <p><a href="{% url 'documents:show-document' document.pk %}" target="_blank"> {{ document }}</a>></p>
                    <form method="POST" action="{% url "documents:delete-document" document.pk %}">
                        {% csrf_token %}
                        <input type="submit" value="DELETE">
                    </form>
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

tasks/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'tasks/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'navbar.html' %}
<div class="main">
    {% block main %}{% endblock %}
</div>

</body>
</html>

tasks/templates/navbar.html
<div class="navbar">
    <p>
        <a href="{% url 'tasks:task-list' %}">tasks</a>
    </p>
    <p>
        <a href="{% url 'documents:list-document' %}">documents</a>
    </p>
</div>

tasks/templates/tasks/task_form.html
{% extends 'base.html' %}
{% block title %}
New task
{% endblock %}
{% block main %}
<div class="task-form">
    <form method="POST" novalidate>
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Save">
    </form>
</div>
{% endblock %}

tasks/templates/tasks/task_list.html
{% extends 'base.html' %}
{% block title %}
    List of tasks
{% endblock %}
{% block main %}
    <div class="task-list">
        <p>Your Tasks! <a href="{% url "tasks:task-create" %}">Create</a></p>
        {% for task in task_list %}
            <div class=task-list__row>
                <p>{{ task.text }} </p>
                <form method="POST" action="{% url "tasks:task-delete" task.pk %}">
                    {% csrf_token %}
                    <input type="submit" value="DELETE">
                </form>
            </div>
        {% endfor %}
        <div>If the background does not have a disgusting color, it means that your css was not found! The only purpose
            of using css here is to make sure that the static files are found. It will look hideous anyway.
        </div>
    </div>
{% endblock %}